<?php $this->load->view('layouts/header');?>
<body>
<div class="navbar navbar-inverse header-con">
    <?php $this->load->view('layouts/logo');?>
  <!--/.navbar-inner--> 
</div>
<div class="container-fluid" id="main-container"> <a id="menu-toggler" href="#"> <span></span> </a>
   <?php $this->load->view('layouts/menu');?>
  <div id="main-content" class="clearfix">
    <div id="breadcrumbs">
      <ul class="breadcrumb">
        <li class="active">Manage Suppliers</li>
      </ul>
      <!--.breadcrumb-->
      
      
    </div>
    <div id="page-content" class="clearfix"> 
     <div class="alert alert-warning" style="width:500px;margin:0 auto">
          <span style="font-size:18px"><b>Tips</b></span>
            <button type="button" class="close" data-dismiss="alert"></button><span id="message">
            <ul>
            <li>The supplier-id is unique and auto generated by system based on the supplier. </li>
            <li>You can upload bulk supplier details through csv file.</li>
            <li>When you click on the names in the column "Name" you will be able to view the supplier informations like "General settings","Transactions","Sales" and "Purchases"</li>
            </ul>
            </span></div>
      <div class="alert alert-info" id="succ_msg" <?php echo ($this->session->flashdata('message') == '')?'style="display:none;"':'';?>><button type="button" class="close" data-dismiss="alert"><i class="icon-remove"></i></button><span id="message"><?php echo ($this->session->flashdata('message')!='')?$this->session->flashdata('message'):'';?></span><br></div>
      <div class="alert alert-error" id="err_msg" <?php echo ($this->session->flashdata('error_message') == '')?'style="display:none;"':'';?>><button type="button" class="close" data-dismiss="alert"><i class="icon-remove"></i></button><span id="message"><?php echo ($this->session->flashdata('error_message')!='')?$this->session->flashdata('error_message'):'';?></span><br></div>
      <!--/.page-header-->
      
      <div class="row-fluid"> 
        <!--PAGE CONTENT BEGINS HERE-->
          <form name="supplier_form" id="supplier_form" method="post">
        <div class="row-fluid">
        <br>
        <button class="btn btn-info" style="float:right; margin-left:10px; margin-bottom:10px;" onClick="window.location.href='<?php echo base_url();?>suppliers/create_supplier'" type="button">+ Create Supplier</button>
          <button class="btn btn-info" style="float:right; margin-left:10px; margin-bottom:10px;" onClick="window.location.href='<?php echo base_url();?>suppliers/bulk_insert'" type="button">Import data from CSV</button>
          <!--<div class="table-header"> Category List </div>-->
          <div class="table-outer">
            	 <table id="table_report" class="table table-striped table-bordered table-hover">
                  <thead>
                    <tr>
                      <!--<th class="center" width="10%"><label><input type="checkbox" name="checkall" id="checkall" class="ace" /><span class="lbl"></span> </label></th>-->
                    <th class="center" width="10%">Supplier ID</th>
                      <th class="center" width="25%">Name</th>
                        <th class="center" width="15%">Outstanding</th>
                         <th class="center" width="15%">Phone No.</th>
				  <?php if($this->session->userdata('session_user_type')=='super_admin' || $this->session->userdata('session_user_type')=='admin'){?>
                    <th class="center" width="10%">Status</th>                                           
                      <th class="center" width="15%">Action</th>
                      <?php } ?>
                    </tr>
                  </thead>
                  <tbody>
				              </tbody>
            </table>
          </div>
             
          
          <div class="clearfix"></div>
          <br/>
        
        </div>
         </form>
        
        <!--PAGE CONTENT ENDS HERE--> 
      </div>
      <div class="clearfix"></div>
      <br/>
      <br/>
            <?php $this->load->view('layouts/footer');?>
      <!--/row--> 
    </div>
    <!--/#page-content--> 
    
    <!--/#ace-settings-container--> 
  </div>
  <!--/#main-content--> 
</div>
<!--/.fluid-container#main-container--> 

<!--<a href="#" id="btn-scroll-up" class="btn btn-small btn-inverse"> <i class="icon-double-angle-up icon-only bigger-110"></i> </a> -->

<!--basic scripts--> 

<?php $this->load->view('layouts/footer_script');?>

<!--page specific plugin scripts--> 
<script src="<?php echo base_url();?>assets/js/jquery.dataTables.min.js"></script> 
<script src="<?php echo base_url();?>assets/js/jquery.dataTables.bootstrap.js"></script> 
<script type="text/javascript">
			$(function() {
				var url = "<?php echo base_url();?>suppliers/ajax_get_suppliers/";  // data tables to load bluk records using ajax
				var oTable1 =$('#table_report').dataTable({
							  "bDestroy": true,
							  "bAutoWidth": false,
				  <?php if($this->session->userdata('session_user_type')=='super_admin' || $this->session->userdata('session_user_type')=='admin'){?>
							  "aoColumnDefs": [{ 'bSortable': false, 'aTargets': [ 0,1,2,3,4,5] }], <?php }
							  else
							  { ?>
							  "aoColumnDefs": [{ 'bSortable': false, 'aTargets': [ 0,1,2,3] }], 
							  <?php }?>
							  
							  "bProcessing": true,
          "bServerSide": true,
							  "bStateSave": true,
							  "oLanguage": {"sProcessing": ""},
          "sAjaxSource":url,
							  "aoColumns": [
                                  {
                                        "fnCreatedCell": function(nTd, sData, oData, iRow, iCol)
                                       {
                                           $(nTd).css('text-align', 'center');
                                       },
                                        "mRender": function (data,type,full) { 
                                                    return data;
                                            }
											},
								  {
											"fnCreatedCell": function(nTd, sData, oData, iRow, iCol)
												   {
													   $(nTd).css('text-align', 'center');
												   },
												"mRender": function (data,type,full) {                          
								 						//return data.substr(0, 1).toUpperCase() + data.substr(1);
									return '<a href="<?php echo base_url()?>suppliers/supplier_general_settings/'+btoa(full[5])+'" target="_blank">'+ data.substr(0, 1).toUpperCase() + data.substr(1)+'</a>';

												}
											},
										{
											"fnCreatedCell": function(nTd, sData, oData, iRow, iCol)
												   {
													   $(nTd).css('text-align', 'center');
												   },
												"mRender": function (data,type,full) {  
													if(data!='')                        
								 						return data;
								 				else
								 						return '0';
												}
											},
										{
													"fnCreatedCell": function(nTd, sData, oData, iRow, iCol)
												   {
													   $(nTd).css('text-align', 'center');
												   },
												"mRender": function (data,type,full) {
													if(data!='')
																return data;
													else
																return '---';
												}
											},
											 <?php if($this->session->userdata('session_user_type')=='super_admin' || $this->session->userdata('session_user_type')=='admin'){?>s
											{
													"fnCreatedCell": function(nTd, sData, oData, iRow, iCol)
												   {
													   $(nTd).css('text-align', 'center');
												   },
												"mRender": function (data,type,full) { 
															var status = '<?php echo STATUS_ACTIVE; ?>';
															if(data==status)
															{
																	status_image = 'active.png';
																	title_msg='Change Inactive';
															}
															else
															{
																	status_image = 'inactive.png';
																	title_msg='Change Active';
															}                           
								 								return '<img style="cursor:pointer;" title="'+title_msg+'" onClick="change_status('+full[5]+',this);" src="<?php echo base_url(); ?>assets/images/'+status_image+'">';
														}
											},
											{
													"fnCreatedCell": function(nTd, sData, oData, iRow, iCol)
												   {
													   $(nTd).css('text-align', 'center');
												   },
												"mRender": function (data,type,full) { 
								 								return '	<div class="btn-group"><a href="<?php echo base_url()?>suppliers/edit_supplier/'+btoa(full[5])+'" class="btn btn-mini btn-info" type="button" title="Edit"><i class="icon-edit bigger-120"></i></a><button type="button" class="btn btn-mini btn-danger" onClick="delete_item('+full[5]+',this)" title="Delete"><i class="icon-trash bigger-120"></i></button></div>';
														}
											}, <?php } ?>
             ],
                             
								});
								
								//end
								
				if(window.location.hash)
				{
					oTable1.fnFilter(window.location.hash.substring(1));
				}				
					
			});
			function fnGetSelected( oTableLocal )
			{
				return oTableLocal.$('tr.row_selected');
			}
			
			function delete_item(supplier_id,element)
			{
				var choice=confirm("Do you wish to continue?");
				if (choice==true)
				{
					var oTable = $('#table_report').dataTable();
					$(element).parents('tr').addClass('row_selected');
					var anSelected = fnGetSelected( oTable );
					$.ajax({
					url: '<?php echo base_url();?>suppliers/delete_item',
					type: 'POST',
					data: { supplier_id:supplier_id },
					success: function(){
						if ( anSelected.length !== 0 )
						 {
							oTable.fnDeleteRow( anSelected[0] );
						 }
						 
						if($("div").find("#succ_msg").attr("class") == "alert alert-info" )
						{
							$("#succ_msg").show();
							$("#succ_msg").html('<button type="button" class="close" data-dismiss="alert"><i class="icon-remove"></i></button>Supplier details has been deleted successfully.<br>');
						}
						else {
							$("#page-content").prepend('<div id="succ_msg" class="alert alert-info"><button type="button" class="close" data-dismiss="alert"><i class="icon-remove"></i></button>Supplier details has been deleted successfully.<br></div>');
						}
					}
					});										
				}
				else
				{
					return false;
				}
			}
			function change_status(supplier_id,element)
			{
                if(confirm("Do you wish to continue?"))
                {
				$.ajax({
					url: '<?php echo base_url();?>suppliers/change_status',
					type: 'POST',
					data: { supplier_id:supplier_id },
					beforeSend: function() { $(element).attr('src','<?php echo base_url();?>'+'assets/images/loader.gif'); },
					success: function(msg){
						if($.trim(msg) == 'inactive')
						{
							$(element).attr('src','<?php echo base_url();?>'+'assets/images/inactive.png');
							$(element).attr('title','Change Active');
						}
						else
						{
							$(element).attr('src','<?php echo base_url();?>'+'assets/images/active.png');
							$(element).attr('title','Change Inactive');
						}
						
						if($("div").find("#succ_msg").attr("class") == "alert alert-info" )
						{
							$("#succ_msg").show();
							$("#succ_msg").html('<button type="button" class="close" data-dismiss="alert"><i class="icon-remove"></i></button>Supplier status has been changed successfully.<br>');
						}
						else {
							$("#page-content").prepend('<div id="succ_msg" class="alert alert-info"><button type="button" class="close" data-dismiss="alert"><i class="icon-remove"></i></button>Supplier status has been changed successfully.<br></div>');
						}
						
					}
					});
                }
                else
                    return false;
			}
		</script>
</body>
</html>
